status: 1
pattern: '[node:field_std_title] [node:field_std_la_fname] [node:field_std_la_lname] ([node:field_std_la_nname])'
escape: false
preserve_titles: false
save: true
chunk: 50
dependencies:
  config:
    - node.type.students
