multiple_registration_hidden_teacher: 1
multiple_registration_form_mode_register_teacher: register
multiple_registration_form_mode_edit_teacher: default
multiple_registration_hidden_accounting_staff: 1
multiple_registration_form_mode_register_accounting_staff: register
multiple_registration_form_mode_edit_accounting_staff: default
multiple_registration_path_students: register/student
multiple_registration_url_students: /user/register/students
multiple_registration_hidden_students: 1
multiple_registration_form_mode_register_students: student
multiple_registration_form_mode_edit_students: student
multiple_registration_path_parents: register/parent
multiple_registration_url_parents: /user/register/parents
multiple_registration_hidden_parents: 1
multiple_registration_form_mode_register_parents: register
multiple_registration_form_mode_edit_parents: default
multiple_registration_path_administration_staff: register/admin-staff
multiple_registration_url_administration_staff: /user/register/administration_staff
multiple_registration_hidden_administration_staff: 1
multiple_registration_form_mode_register_administration_staff: register
multiple_registration_form_mode_edit_administration_staff: default
multiple_registration_path_accounting_staff: register/account-staff
multiple_registration_url_accounting_staff: /user/register/accounting_staff
multiple_registration_path_teacher: register/teaching-staff
multiple_registration_url_teacher: /user/register/teacher
