multiple_registration_pages_white_list:
  anonymous: 0
  authenticated: 0
  administrator: 0
  maestro_example: 0
  board_of_management: 0
  managing_director: 0
  deputy_managing_director: 0
  administration_staff: 0
  accounting_staff: 0
  teacher: 0
  students: 0
  parents: 0
  demo_region_admin: 0
  demo_region_user: 0
